### Pegar uma banda.
GET http://localhost:3003/band/:name/:id
Authorization:

### Criar um usuário.
POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Astrodev",
    "email": "astrodev@email.com",
    "password": "#AsdF12",
    "role": "ADMIN"
}

### Fazer login. 
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email": "astrodev@email.com", 
    "password": "#AsdF12"
}

### Criar uma Banda.
POST http://localhost:3003/band
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjUwOTM3OWRjLTNiNjUtNGU4OC1iZTZjLTE5YjhhZTEwZGFlMiJ9LCJpYXQiOjE2NTcyMTMzODUsImV4cCI6MTY1NzIxNTE4NX0.dDdtFloFqLLE7OU4Vat_hJyQ5vOsGtErvhVtI1iJLYA

{
    "name": "Scorpions",
    "musicGenre": "Rock",
    "responsible": "Klaus Meine"
}

### Ver detalhes de uma banda.
Get http://localhost:3003/band/8bc90f27-1193-49f7-9244-4ef548a0af48
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjUwOTM3OWRjLTNiNjUtNGU4OC1iZTZjLTE5YjhhZTEwZGFlMiJ9LCJpYXQiOjE2NTcyMTMzODUsImV4cCI6MTY1NzIxNTE4NX0.dDdtFloFqLLE7OU4Vat_hJyQ5vOsGtErvhVtI1iJLYA


### Criar uma Banda.
POST http://localhost:3003/show
Content-Type: application/json
Authorization:

{
    "weekDay":"Domingo",
    "startTime": 08,
    "endTime": 10,
    "bandId":""
}