### Pegar uma banda.
GET http://localhost:3003/band/:name/:id
Authorization:

### Criar um usuário.
POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Astrodev4",
    "email": "astrodev4@email.com",
    "password": "#AsdF12"
}

### Fazer login. 
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email": "astrodev@email.com", 
    "password": "123456"
}

### Criar uma Banda.
POST http://localhost:3003/band
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6ImNjN2M4ZjE2LTcyZGQtNDM1MS1hYTUxLTc2ZTNmODQ0ZjUxYiJ9LCJpYXQiOjE2NTcyMTE0MjMsImV4cCI6MTY1NzIxMzIyM30.avGx8UOVeFgBpl71dM6QpqK5ogPx3Y_j2MyH3aoZYrw

{
    "name": "Scorpions",
    "musicGenre": "Rock",
    "responsible": "Klaus Meine"
}

### Criar uma Banda.
POST http://localhost:3003/show
Content-Type: application/json
Authorization:

{
    "weekDay":"Domingo",
    "startTime": 08,
    "endTime": 10,
    "bandId":""
}