CREATE TABLE IF NOT EXISTS LAMA_USUARIOS (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM("NORMAL", "ADMIN") NOT NULL DEFAULT "NORMAL"
);

CREATE TABLE IF NOT EXISTS LAMA_BANDAS (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  music_genre VARCHAR(255) NOT NULL,
  responsible VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS LAMA_SHOWS (
  id VARCHAR(255) PRIMARY KEY,
  week_day VARCHAR(255) NOT NULL,
  start_time INT NOT NULL,
  end_time INT NOT NULL,
  band_id VARCHAR(255) NOT NULL,
  FOREIGN KEY(band_id) REFERENCES LAMA_BANDAS(id)
);


DESCRIBE LAMA_USUARIOS;
DESCRIBE LAMA_BANDAS;
DESCRIBE LAMA_SHOWS;

DROP TABLE LAMA_USUARIOS;
DROP TABLE LAMA_BANDAS;
DROP TABLE LAMA_SHOWS;